/**
 * IntroductionDeversiFiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ETH
 */
class ETH extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.decimals = this.constructor.getValue(obj.decimals);
        this.wrapperAddress = this.constructor.getValue(obj.wrapperAddress);
        this.minOrderSize = this.constructor.getValue(obj.minOrderSize);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'decimals', realName: 'decimals' },
            { name: 'wrapperAddress', realName: 'wrapperAddress' },
            { name: 'minOrderSize', realName: 'minOrderSize' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ETH;
