/**
 * IntroductionDeversiFiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EventIDInfo
 */
class EventIDInfo extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id || obj._id);
        this.uSDValue = this.constructor.getValue(obj.uSDValue || obj.USDValue);
        this.blockNumber = this.constructor.getValue(obj.blockNumber);
        this.createdAt = this.constructor.getValue(obj.createdAt);
        this.date = this.constructor.getValue(obj.date);
        this.logIndex = this.constructor.getValue(obj.logIndex);
        this.maker = this.constructor.getValue(obj.maker);
        this.taker = this.constructor.getValue(obj.taker);
        this.timestamp = this.constructor.getValue(obj.timestamp);
        this.txHash = this.constructor.getValue(obj.txHash);
        this.type = this.constructor.getValue(obj.type);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: '_id' },
            { name: 'uSDValue', realName: 'USDValue' },
            { name: 'blockNumber', realName: 'blockNumber' },
            { name: 'createdAt', realName: 'createdAt' },
            { name: 'date', realName: 'date' },
            { name: 'logIndex', realName: 'logIndex' },
            { name: 'maker', realName: 'maker', type: 'Maker' },
            { name: 'taker', realName: 'taker', type: 'Taker' },
            { name: 'timestamp', realName: 'timestamp' },
            { name: 'txHash', realName: 'txHash' },
            { name: 'type', realName: 'type' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = EventIDInfo;
