/**
 * IntroductionDeversiFiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Transaction
 */
class Transaction extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.events = this.constructor.getValue(obj.events);
        this.id = this.constructor.getValue(obj.id || obj._id);
        this.eTHUSDPrice = this.constructor.getValue(obj.eTHUSDPrice || obj.ETHUSDPrice);
        this.blockNumber = this.constructor.getValue(obj.blockNumber);
        this.createdAt = this.constructor.getValue(obj.createdAt);
        this.date = this.constructor.getValue(obj.date);
        this.gasPrice = this.constructor.getValue(obj.gasPrice);
        this.gasUsed = this.constructor.getValue(obj.gasUsed);
        this.numEvents = this.constructor.getValue(obj.numEvents);
        this.priceETH = this.constructor.getValue(obj.priceETH);
        this.priceUSD = this.constructor.getValue(obj.priceUSD);
        this.timestamp = this.constructor.getValue(obj.timestamp);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'events', realName: 'events', array: true, type: 'Event' },
            { name: 'id', realName: '_id' },
            { name: 'eTHUSDPrice', realName: 'ETHUSDPrice' },
            { name: 'blockNumber', realName: 'blockNumber' },
            { name: 'createdAt', realName: 'createdAt' },
            { name: 'date', realName: 'date' },
            { name: 'gasPrice', realName: 'gasPrice' },
            { name: 'gasUsed', realName: 'gasUsed' },
            { name: 'numEvents', realName: 'numEvents' },
            { name: 'priceETH', realName: 'priceETH' },
            { name: 'priceUSD', realName: 'priceUSD' },
            { name: 'timestamp', realName: 'timestamp' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Transaction;
